# Generated by Django 4.0.5 on 2022-06-19 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmeti',
            name='nositelj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='role',
            field=models.CharField(choices=[('prof', 'profesor'), ('stu', 'student'), ('admin', 'administrator')], max_length=50),
        ),
    ]
